// examples/web_ui/frontend/src/components/dialog/AgentDialog.tsx
import { CircleAlert, Loader2, PlusCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { ContextConfig, ReActConfig } from '@/api';
import {
	AgentFormFields,
	defaultAgentFormValues,
	type AgentFormValues,
	type AgentSection,
} from '@/components/form/AgentFormFields';
import type { SchemaFormValue } from '@/components/form/SchemaForm';
import { Button } from '@/components/ui/button';
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogDescription,
	DialogTrigger,
} from '@/components/ui/dialog';
import { useAgents } from '@/hooks/useAgents';
import { useAgentSchema } from '@/hooks/useAgentSchema';

interface Props {
	onCreated?: () => void;
	triggerId?: string;
}

export function AgentDialog({ onCreated, triggerId }: Props) {
	const { create } = useAgents();
	const { t } = useTranslation();
	const { schema } = useAgentSchema();
	const [open, setOpen] = useState(false);
	const [submitting, setSubmitting] = useState(false);
	const [values, setValues] = useState<AgentFormValues | null>(null);

	useEffect(() => {
		if (open && schema && !values) {
			setValues(defaultAgentFormValues(schema));
		}
		if (!open) setValues(null);
	}, [open, schema, values]);

	const handleChange = (section: AgentSection, key: string, value: SchemaFormValue) => {
		setValues((prev) =>
			prev ? { ...prev, [section]: { ...prev[section], [key]: value } } : prev,
		);
	};

	const handleSubmit = async () => {
		if (!values) return;
		const name = (values.identity.name as string | undefined)?.trim();
		if (!name) return;
		setSubmitting(true);
		try {
			await create({
				name,
				system_prompt: values.identity.system_prompt as string | undefined,
				context_config: values.context_config as unknown as ContextConfig,
				react_config: values.react_config as unknown as ReActConfig,
			});
			setOpen(false);
			onCreated?.();
		} finally {
			setSubmitting(false);
		}
	};

	const nameValid = !!(values?.identity.name as string | undefined)?.trim();

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button id={triggerId}>
					<PlusCircle />
					<span>{t('dialog-agent-create.trigger')}</span>
				</Button>
			</DialogTrigger>
			<DialogContent className="!w-[500px] !max-w-[500px]">
				<DialogHeader>
					<DialogTitle>{t('dialog-agent-create.title')}</DialogTitle>
					<DialogDescription className="sr-only">
						{t('dialog-agent-create.description')}
					</DialogDescription>
				</DialogHeader>
				<div className="no-scrollbar -mx-4 max-h-[75vh] overflow-y-auto px-4">
					{schema && values ? (
						<AgentFormFields schema={schema} values={values} onChange={handleChange} />
					) : (
						<p className="text-muted-foreground text-sm">{t('common.loading')}</p>
					)}
				</div>
				<DialogFooter>
					<Button variant="ghost" onClick={() => setOpen(false)} disabled={submitting}>
						<CircleAlert className="size-3.5" />
						{t('common.cancel')}
					</Button>
					<Button
						onClick={handleSubmit}
						disabled={!nameValid || submitting || !schema || !values}
					>
						{submitting ? (
							<Loader2 className="size-3.5 animate-spin" />
						) : (
							<PlusCircle className="size-3.5" />
						)}
						{submitting ? t('common.creating') : t('common.create')}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// examples/web_ui/frontend-vue/src/components/dialog/AgentDialog.vue
<template>
  <ElDialog :model-value="open" :width="500" @update:model-value="$emit('update:open', $event)" top="5vh">
    <template #header>
      <h3 class="text-lg font-semibold">{{ t('dialog-agent-create.title') }}</h3>
    </template>
    <div class="-mx-4 max-h-[75vh] overflow-y-auto px-4">
      <AgentFormFields v-if="schema && formValues" :schema="schema as any" :values="formValues" />
      <p v-else class="text-sm text-muted-foreground">{{ t('common.loading') }}</p>
    </div>
    <template #footer>
      <ElButton @click="$emit('update:open', false)" :disabled="submitting">
        <CircleAlert class="size-3.5 mr-1" />{{ t('common.cancel') }}
      </ElButton>
      <ElButton type="primary" @click="handleSubmit" :disabled="!nameValid || submitting || !schema || !formValues">
        <ElIcon class="mr-1">
          <Loader2 v-if="submitting" class="animate-spin" />
          <PlusCircle v-else />
        </ElIcon>
        {{ submitting ? t('common.creating') : t('common.create') }}
      </ElButton>
    </template>
  </ElDialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { ElDialog, ElButton, ElIcon } from 'element-plus';
import { CircleAlert, Loader2, PlusCircle } from 'lucide-vue-next';
import { useAgents } from '@/composables/useAgents';
import { useAgentSchema } from '@/composables/useAgentSchema';
import { useTranslation } from '@/i18n/useI18n';
import AgentFormFields from '@/components/form/AgentFormFields.vue';
import { defaultAgentFormValues } from '@/components/form/AgentFormFields';
import type { AgentFormValues } from '@/components/form/AgentFormFields';
import type { ContextConfig, ReActConfig } from '@/api';

const props = defineProps<{
  open: boolean;
  onCreated?: () => void;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
}>();

const { t } = useTranslation();
const { create } = useAgents();
const { schema } = useAgentSchema();
const submitting = ref(false);
const formValues = ref<AgentFormValues | null>(null);

watch(() => props.open, (val) => {
  if (val && schema.value && !formValues.value) {
    formValues.value = defaultAgentFormValues(schema.value as any);
  }
  if (!val) formValues.value = null;
});

const nameValid = computed(() => {
  const name = formValues.value?.identity?.name as string | undefined;
  return !!(name?.trim());
});

async function handleSubmit() {
  if (!formValues.value) return;
  const name = (formValues.value.identity.name as string | undefined)?.trim();
  if (!name) return;
  submitting.value = true;
  try {
    await create({
      name,
      system_prompt: formValues.value.identity.system_prompt as string | undefined,
      context_config: formValues.value.context_config as unknown as ContextConfig,
      react_config: formValues.value.react_config as unknown as ReActConfig,
    });
    emit('update:open', false);
    props.onCreated?.();
  } finally {
    submitting.value = false;
  }
}
</script>
