// examples/web_ui/frontend/src/components/dialog/RenameSessionDialog.tsx
import { CheckCircle, CircleAlert, Loader2 } from 'lucide-react';
import { useState, useEffect } from 'react';

import { Button } from '@/components/ui/button';
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogDescription,
} from '@/components/ui/dialog';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { useTranslation } from '@/i18n/useI18n';

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	currentName: string;
	onConfirm: (name: string) => Promise<void>;
}

export function RenameSessionDialog({ open, onOpenChange, currentName, onConfirm }: Props) {
	const { t } = useTranslation();
	const [name, setName] = useState(currentName);
	const [loading, setLoading] = useState(false);

	useEffect(() => {
		if (open) setName(currentName);
	}, [open, currentName]);

	const handleConfirm = async () => {
		if (!name.trim()) return;
		setLoading(true);
		try {
			await onConfirm(name.trim());
			onOpenChange(false);
		} finally {
			setLoading(false);
		}
	};

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>{t('dialog-session-rename.title')}</DialogTitle>
					<DialogDescription>{t('dialog-session-rename.description')}</DialogDescription>
				</DialogHeader>
				<FieldGroup>
					<Field>
						<FieldLabel>{t('dialog-session-rename.label')}</FieldLabel>
						<Input
							value={name}
							onChange={(e) => setName(e.target.value)}
							placeholder={t('dialog-session-rename.placeholder')}
							onKeyDown={(e) => {
								if (e.key === 'Enter') handleConfirm();
							}}
							autoFocus
						/>
					</Field>
				</FieldGroup>
				<DialogFooter>
					<Button variant="ghost" onClick={() => onOpenChange(false)} disabled={loading}>
						<CircleAlert className="size-3.5" />
						{t('common.cancel')}
					</Button>
					<Button onClick={handleConfirm} disabled={loading || !name.trim()}>
						{loading ? (
							<Loader2 className="size-3.5 animate-spin" />
						) : (
							<CheckCircle className="size-3.5" />
						)}
						{t('common.confirm')}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}

// examples/web_ui/frontend-vue/src/components/dialog/RenameSessionDialog.vue
<template>
  <ElDialog :model-value="open" :width="400" @update:model-value="$emit('update:open', $event)">
    <template #header>
      <h3 class="text-lg font-semibold">{{ t('dialog-session-rename.title') }}</h3>
      <p class="text-sm text-muted-foreground mt-1">{{ t('dialog-session-rename.description') }}</p>
    </template>
    <ElForm>
      <ElFormItem :label="t('dialog-session-rename.label')">
        <ElInput
          v-model="name"
          :placeholder="t('dialog-session-rename.placeholder')"
          @keydown.enter="handleConfirm"
          autofocus
        />
      </ElFormItem>
    </ElForm>
    <template #footer>
      <ElButton @click="$emit('update:open', false)" :disabled="loading">
        <CircleAlert class="size-3.5 mr-1" />{{ t('common.cancel') }}
      </ElButton>
      <ElButton type="primary" @click="handleConfirm" :disabled="loading || !name.trim()">
        <ElIcon class="mr-1">
          <Loader2 v-if="loading" class="animate-spin" />
          <CircleCheck v-else />
        </ElIcon>
        {{ t('common.confirm') }}
      </ElButton>
    </template>
  </ElDialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { ElDialog, ElButton, ElForm, ElFormItem, ElInput, ElIcon } from 'element-plus';
import { CircleAlert, CircleCheck, Loader2 } from 'lucide-vue-next';
import { useTranslation } from '@/i18n/useI18n';

const props = defineProps<{
  open: boolean;
  currentName: string;
  onConfirm: (name: string) => Promise<void>;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
}>();

const { t } = useTranslation();
const name = ref(props.currentName);
const loading = ref(false);

watch(() => props.open, (val) => {
  if (val) name.value = props.currentName;
});

async function handleConfirm() {
  if (!name.value.trim()) return;
  loading.value = true;
  try {
    await props.onConfirm(name.value.trim());
    emit('update:open', false);
  } finally {
    loading.value = false;
  }
}
</script>
