// examples/web_ui/frontend-vue/src/components/dialog/EditAgentDialog.vue
<template>
  <ElDialog :model-value="open" :width="500" @update:model-value="$emit('update:open', $event)" top="5vh">
    <template #header>
      <h3 class="text-lg font-semibold">{{ t('dialog-agent-edit.title') }}</h3>
    </template>
    <div class="-mx-4 max-h-[75vh] overflow-y-auto px-4">
      <AgentFormFields v-if="schema && formValues" :schema="schema as any" :values="formValues" />
      <p v-else class="text-sm text-muted-foreground">{{ t('common.loading') }}</p>
    </div>
    <template #footer>
      <ElButton @click="$emit('update:open', false)" :disabled="submitting">
        <CircleAlert class="size-3.5 mr-1" />{{ t('common.cancel') }}
      </ElButton>
      <ElButton type="primary" @click="handleSubmit" :disabled="!nameValid || submitting || !schema || !formValues">
        <ElIcon class="mr-1">
          <Loader2 v-if="submitting" class="animate-spin" />
          <Save v-else />
        </ElIcon>
        {{ submitting ? t('common.saving') : t('common.save') }}
      </ElButton>
    </template>
  </ElDialog>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { ElDialog, ElButton, ElIcon } from 'element-plus';
import { CircleAlert, Loader2, Save } from 'lucide-vue-next';
import { useAgents } from '@/composables/useAgents';
import { useAgentSchema } from '@/composables/useAgentSchema';
import { useTranslation } from '@/i18n/useI18n';
import AgentFormFields from '@/components/form/AgentFormFields.vue';
import { defaultAgentFormValues } from '@/components/form/AgentFormFields';
import type { AgentFormValues } from '@/components/form/AgentFormFields';
import type { AgentRecord, ContextConfig, ReActConfig } from '@/api';

const props = defineProps<{
  open: boolean;
  agent: AgentRecord | null;
  onUpdated?: () => void;
}>();

const emit = defineEmits<{
  'update:open': [value: boolean];
}>();

const { t } = useTranslation();
const { update } = useAgents();
const { schema } = useAgentSchema();
const submitting = ref(false);
const formValues = ref<AgentFormValues | null>(null);

watch(() => props.open, (val) => {
  if (!val || !schema.value || !props.agent) {
    if (!val) formValues.value = null;
    return;
  }
  const base = defaultAgentFormValues(schema.value as any);
  const d = props.agent.data;
  formValues.value = {
    identity: {
      ...base.identity,
      name: d.name,
      system_prompt: d.system_prompt,
    },
    context_config: { ...base.context_config, ...(d.context_config ?? {}) },
    react_config: { ...base.react_config, ...(d.react_config ?? {}) },
  };
});

const nameValid = computed(() => {
  const name = formValues.value?.identity?.name as string | undefined;
  return !!(name?.trim());
});

async function handleSubmit() {
  if (!formValues.value || !props.agent) return;
  const name = (formValues.value.identity.name as string | undefined)?.trim();
  if (!name) return;
  submitting.value = true;
  try {
    await update(props.agent.id, {
      name,
      system_prompt: formValues.value.identity.system_prompt as string | undefined,
      context_config: formValues.value.context_config as unknown as ContextConfig,
      react_config: formValues.value.react_config as unknown as ReActConfig,
    });
    emit('update:open', false);
    props.onUpdated?.();
  } finally {
    submitting.value = false;
  }
}
</script>

// examples/web_ui/frontend/src/components/dialog/EditAgentDialog.tsx
import { CircleAlert, Loader2, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

import type { AgentRecord, ContextConfig, ReActConfig } from '@/api';
import {
	AgentFormFields,
	defaultAgentFormValues,
	type AgentFormValues,
	type AgentSection,
} from '@/components/form/AgentFormFields';
import type { SchemaFormValue } from '@/components/form/SchemaForm';
import { Button } from '@/components/ui/button';
import {
	Dialog,
	DialogContent,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogDescription,
} from '@/components/ui/dialog';
import { useAgents } from '@/hooks/useAgents';
import { useAgentSchema } from '@/hooks/useAgentSchema';

interface Props {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	agent: AgentRecord;
	onUpdated?: () => void;
}

export function EditAgentDialog({ open, onOpenChange, agent, onUpdated }: Props) {
	const { update } = useAgents();
	const { t } = useTranslation();
	const { schema } = useAgentSchema();
	const [submitting, setSubmitting] = useState(false);
	const [values, setValues] = useState<AgentFormValues | null>(null);

	useEffect(() => {
		if (!open || !schema) {
			if (!open) setValues(null);
			return;
		}
		// Start from schema defaults, then overlay the existing agent's data so
		// any unset fields fall back to defaults rather than empty.
		const base = defaultAgentFormValues(schema);
		const d = agent.data;
		setValues({
			identity: {
				...base.identity,
				name: d.name,
				system_prompt: d.system_prompt,
			},
			context_config: { ...base.context_config, ...(d.context_config ?? {}) },
			react_config: { ...base.react_config, ...(d.react_config ?? {}) },
		});
	}, [open, schema, agent]);

	const handleChange = (section: AgentSection, key: string, value: SchemaFormValue) => {
		setValues((prev) =>
			prev ? { ...prev, [section]: { ...prev[section], [key]: value } } : prev,
		);
	};

	const handleSubmit = async () => {
		if (!values) return;
		const name = (values.identity.name as string | undefined)?.trim();
		if (!name) return;
		setSubmitting(true);
		try {
			await update(agent.id, {
				name,
				system_prompt: values.identity.system_prompt as string | undefined,
				context_config: values.context_config as unknown as ContextConfig,
				react_config: values.react_config as unknown as ReActConfig,
			});
			onOpenChange(false);
			onUpdated?.();
		} finally {
			setSubmitting(false);
		}
	};

	const nameValid = !!(values?.identity.name as string | undefined)?.trim();

	return (
		<Dialog open={open} onOpenChange={onOpenChange}>
			<DialogContent className="!w-[500px] !max-w-[500px]">
				<DialogHeader>
					<DialogTitle>{t('dialog-agent-edit.title')}</DialogTitle>
					<DialogDescription className="sr-only">
						{t('dialog-agent-edit.description')}
					</DialogDescription>
				</DialogHeader>
				<div className="no-scrollbar -mx-4 max-h-[75vh] overflow-y-auto px-4">
					{schema && values ? (
						<AgentFormFields schema={schema} values={values} onChange={handleChange} />
					) : (
						<p className="text-muted-foreground text-sm">{t('common.loading')}</p>
					)}
				</div>
				<DialogFooter>
					<Button
						variant="ghost"
						onClick={() => onOpenChange(false)}
						disabled={submitting}
					>
						<CircleAlert className="size-3.5" />
						{t('common.cancel')}
					</Button>
					<Button
						onClick={handleSubmit}
						disabled={!nameValid || submitting || !schema || !values}
					>
						{submitting ? (
							<Loader2 className="size-3.5 animate-spin" />
						) : (
							<Save className="size-3.5" />
						)}
						{submitting ? t('common.saving') : t('common.save')}
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	);
}
