// examples/web_ui/frontend-vue/src/components/schedule/ScheduleCard.vue
<template>
  <div class="flex items-center gap-3 rounded-lg border p-4 cursor-pointer hover:shadow-md transition-shadow" @click="$emit('click')">
    <ElIcon :size="20">
      <Bot v-if="schedule.data.enabled" />
      <BotOff v-else />
    </ElIcon>
    <div class="flex-1 min-w-0">
      <div class="font-[550] truncate">{{ schedule.data.name }}</div>
      <div class="flex gap-x-2 items-center text-xs mt-1">
        <ElTag v-if="!schedule.data.enabled" size="small" type="info">
          <Pause class="h-3 w-3 mr-1" />{{ t('common.disabled') }}
        </ElTag>
        <span class="text-muted-foreground">
          <Calendar class="size-3 inline mr-1" />
          {{ formatDate(schedule.data.started_at) }}
          <ArrowRight v-if="schedule.data.ended_at" class="size-3 inline mx-1" />
          {{ schedule.data.ended_at ? formatDate(schedule.data.ended_at) : '' }}
          {{ parsed.time }}
        </span>
        <span class="text-muted-foreground">
          <ClipboardClock class="size-3 inline mr-1" />
          {{ getFrequencyLabel(parsed, t) }}
        </span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { ElIcon, ElTag } from 'element-plus';
import { Bot, BotOff, Pause, Calendar, ArrowRight, ClipboardClock } from 'lucide-vue-next';
import type { ScheduleRecord } from '@/api';
import { parseCronExpression, getFrequencyLabel } from './schedule-utils';
import { useTranslation } from '@/i18n/useI18n';

const props = defineProps<{
  schedule: ScheduleRecord;
}>();

defineEmits<{
  click: [];
}>();

const { t } = useTranslation();

const parsed = computed(() => parseCronExpression(props.schedule.data.cron_expression, props.schedule.data.started_at));

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString();
  } catch {
    return dateStr;
  }
}
</script>

// examples/web_ui/frontend/src/pages/schedule/schedule-card.tsx
import { Pause, Calendar, ArrowRight, Bot, ClipboardClock, BotOff } from 'lucide-react';

import { parseCronExpression, getFrequencyLabel } from './schedule-utils';
import type { ScheduleRecord } from '@/api';
import { Badge } from '@/components/ui/badge';
import { Item, ItemContent, ItemDescription, ItemMedia, ItemTitle } from '@/components/ui/item';
import { useTranslation } from '@/i18n/useI18n';

interface ScheduleCardProps {
	schedule: ScheduleRecord;
	onClick: () => void;
}

export function ScheduleCard({ schedule, onClick }: ScheduleCardProps) {
	const { t } = useTranslation();
	const { data } = schedule;
	const parsed = parseCronExpression(data.cron_expression, data.started_at);

	return (
		<Item className="cursor-pointer hover:shadow-md" variant="outline" onClick={onClick}>
			<ItemMedia variant="icon">{data.enabled ? <Bot /> : <BotOff />}</ItemMedia>
			<ItemContent>
				<ItemTitle className="font-[550] truncate max-w-full">{data.name}</ItemTitle>
				<ItemDescription className="flex gap-x-2 items-center text-xs truncate overflow-hidden">
					{!data.enabled && (
						<Badge variant="secondary" className="gap-1">
							<Pause className="h-3 w-3" />
							{t('common.disabled')}
						</Badge>
					)}
					<Badge variant="link" className="pl-0">
						<Calendar data-icon="inline-start" />
						{new Date(data.started_at).toLocaleDateString()}
						{data.ended_at && (
							<div className="flex items-center gap-1">
								<ArrowRight className="size-3 text-muted-foreground" />
								{new Date(data.ended_at).toLocaleDateString()}
							</div>
						)}
						<div>{parsed.time}</div>
					</Badge>
					<Badge variant="link">
						<ClipboardClock data-icon="inline-start" />
						{getFrequencyLabel(parsed, t)}
					</Badge>
				</ItemDescription>
			</ItemContent>
		</Item>
	);
}
