// examples/web_ui/frontend-vue/src/views/setup/index.vue
<template>
  <div class="flex items-center justify-center h-screen w-screen bg-background text-foreground">
    <div class="flex flex-col gap-6 w-full max-w-sm px-4">
      <div class="rounded-xl border bg-card text-card-foreground shadow-sm">
        <div class="flex flex-col space-y-1.5 p-6">
          <h3 class="font-semibold tracking-tight text-xl">{{ t('setup.title') }}</h3>
          <p class="text-sm text-muted-foreground">{{ t('setup.description') }}</p>
        </div>
        <div class="p-6 pt-0">
          <ElForm label-position="top" @submit.prevent="handleSubmit">
            <ElFormItem :label="t('setup.serverUrl')" required>
              <ElInput
                v-model="url"
                type="url"
                :placeholder="t('setup.serverUrlPlaceholder')"
              />
            </ElFormItem>
            <ElFormItem :label="t('setup.username')" required>
              <ElInput
                v-model="username"
                type="text"
                :placeholder="t('setup.usernamePlaceholder')"
              />
            </ElFormItem>
            <ElFormItem>
              <ElButton type="primary" native-type="submit" class="w-full">
                {{ t('setup.submit') }}
              </ElButton>
            </ElFormItem>
          </ElForm>
        </div>
      </div>
      <p class="px-6 text-center text-sm text-muted-foreground">{{ t('setup.hint') }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { ElInput, ElButton, ElForm, ElFormItem } from 'element-plus';
import { useTranslation } from '@/i18n/useI18n';

const emit = defineEmits<{
  complete: [];
}>();

const { t } = useTranslation();

const url = ref('');
const username = ref('');

onMounted(() => {
  url.value = localStorage.getItem('server_url') ?? '';
  username.value = localStorage.getItem('username') ?? '';
});

function handleSubmit() {
  if (!url.value || !username.value) return;
  localStorage.setItem('server_url', url.value);
  localStorage.setItem('username', username.value);
  emit('complete');
}
</script>

// examples/web_ui/frontend/src/pages/setup/index.tsx
import { useState } from 'react';

import { Button } from '@/components/ui/button.tsx';
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from '@/components/ui/card.tsx';
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field.tsx';
import { Input } from '@/components/ui/input.tsx';
import { useTranslation } from '@/i18n/useI18n.ts';
import { cn } from '@/lib/utils.ts';

interface Props {
	onComplete: () => void;
	className?: string;
}

export const SetupPage = ({ onComplete, className }: Props) => {
	const { t } = useTranslation();
	const [url, setUrl] = useState(() => localStorage.getItem('server_url') ?? '');
	const [username, setUsername] = useState(() => localStorage.getItem('username') ?? '');

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault();
		localStorage.setItem('server_url', url);
		localStorage.setItem('username', username);
		onComplete();
	};

	return (
		<div className="flex items-center justify-center h-full">
			<div className={cn('flex flex-col gap-6 w-full max-w-sm', className)}>
				<Card>
					<CardHeader>
						<CardTitle>{t('setup.title')}</CardTitle>
						<CardDescription>{t('setup.description')}</CardDescription>
					</CardHeader>
					<CardContent>
						<form onSubmit={handleSubmit}>
							<FieldGroup>
								<Field>
									<FieldLabel htmlFor="server-url-input">
										{t('setup.serverUrl')}
									</FieldLabel>
									<Input
										id="server-url-input"
										type="url"
										placeholder={t('setup.serverUrlPlaceholder')}
										value={url}
										onChange={(e) => setUrl(e.target.value)}
										required
									/>
								</Field>
								<Field>
									<FieldLabel htmlFor="username-input">
										{t('setup.username')}
									</FieldLabel>
									<Input
										id="username-input"
										type="text"
										placeholder={t('setup.usernamePlaceholder')}
										value={username}
										onChange={(e) => setUsername(e.target.value)}
										required
									/>
								</Field>
								<Field>
									<Button type="submit" className="w-full">
										{t('setup.submit')}
									</Button>
								</Field>
							</FieldGroup>
						</form>
					</CardContent>
				</Card>
				<FieldDescription className="px-6 text-center">{t('setup.hint')}</FieldDescription>
			</div>
		</div>
	);
};
