// examples/web_ui/frontend/src/components/chat/ChatContent.tsx
import type { ContentBlock, Msg, ToolCallBlock } from '@agentscope-ai/agentscope/message';
import React from 'react';
import { useRef, useEffect } from 'react';

import { EmptyMessage } from './Empty';
import { MessageBubble } from '@/components/chat/MessageBubble';
import { TextInput } from '@/components/chat/TextInput.tsx';
import { cn } from '@/lib/utils';

interface ChatContentProps {
	msgs: Msg[];
	sending: boolean;
	disabled: boolean;
	onSend: (content: ContentBlock[]) => void;
	onUserConfirm: (
		toolCall: ToolCallBlock,
		confirm: boolean,
		replyId: string,
		rules?: ToolCallBlock['suggested_rules'],
	) => void;
	autoComplete?: (input: string) => string | null;
	className?: string;
	/**
	 * Optional content pinned at the bottom of the chat — between the
	 * message scroll area and the text input (e.g. pending subagent HITL
	 * cards on a team leader's view). Rendered below the conversation so
	 * a pending confirmation sits next to the input, where the user is
	 * looking, rather than scrolled off the top.
	 */
	footerSlot?: React.ReactNode;
	/** @see TextInputProps.allowedInputTypes */
	allowedInputTypes: string[];
	/** @see TextInputProps.fileProcessor */
	fileProcessor: (file: File) => Promise<ContentBlock | null>;
}

const ChatContentComponent: React.FC<ChatContentProps> = ({
	msgs,
	sending,
	disabled,
	onSend,
	onUserConfirm,
	autoComplete,
	className,
	footerSlot,
	allowedInputTypes,
	fileProcessor,
}) => {
	const scrollAreaRef = useRef<HTMLDivElement>(null);
	const prevMsgCountRef = useRef<number>(0);
	const wasNearBottomRef = useRef<boolean>(true);

	// Auto-scroll to bottom only if user is already near the bottom
	useEffect(() => {
		const currentCount = msgs.length;
		const prevCount = prevMsgCountRef.current;

		const shouldCheck =
			(currentCount > prevCount && prevCount > 0) || (sending && prevCount > 0);

		if (shouldCheck && scrollAreaRef.current) {
			const { scrollHeight } = scrollAreaRef.current;

			// Check if user was near bottom before content changed
			const isNearBottom = wasNearBottomRef.current;

			if (isNearBottom) {
				scrollAreaRef.current.scrollTo({
					top: scrollHeight,
					behavior: 'smooth',
				});
			}
		}

		prevMsgCountRef.current = currentCount;
	}, [msgs, sending]);

	// Track if user is near bottom whenever they scroll
	useEffect(() => {
		const scrollArea = scrollAreaRef.current;
		if (!scrollArea) return;

		const handleScroll = () => {
			const { scrollTop, scrollHeight, clientHeight } = scrollArea;
			wasNearBottomRef.current = scrollTop + clientHeight >= scrollHeight - 50;
		};

		scrollArea.addEventListener('scroll', handleScroll);
		return () => scrollArea.removeEventListener('scroll', handleScroll);
	}, []);

	return (
		<div className={cn('flex flex-col h-full w-full items-center p-2 gap-4', className)}>
			<div
				ref={scrollAreaRef}
				className="flex-1 w-full max-w-full overflow-auto no-scrollbar overflow-x-hidden"
			>
				<div className="flex flex-col gap-4 size-full max-w-full">
					{msgs.length > 0 ? (
						msgs.map((message) => (
							<MessageBubble
								key={message.id}
								message={message}
								onUserConfirm={onUserConfirm}
							/>
						))
					) : (
						<EmptyMessage />
					)}
				</div>
			</div>
			{footerSlot ? <div className="w-full max-w-full shrink-0">{footerSlot}</div> : null}
			<TextInput
				className="min-w-full max-w-full w-full"
				onSend={onSend}
				disabled={disabled}
				autoComplete={autoComplete}
				allowedInputTypes={allowedInputTypes}
				fileProcessor={fileProcessor}
			/>
		</div>
	);
};

export const ChatContent = React.memo(ChatContentComponent);

// examples/web_ui/frontend-vue/src/components/chat/ChatContent.vue
<template>
  <div :class="['flex flex-col h-full w-full items-center p-2 gap-4', className]">
    <div
      ref="scrollAreaRef"
      class="flex-1 w-full max-w-full overflow-auto no-scrollbar overflow-x-hidden"
      @scroll="handleScroll"
    >
      <div class="flex flex-col gap-4 size-full max-w-full">
        <MessageBubble
          v-for="message in msgs"
          :key="message.id"
          :message="message"
          :on-user-confirm="onUserConfirm"
        />
        <Empty v-if="msgs.length === 0" />
      </div>
    </div>
    <div v-if="$slots.footer" class="w-full max-w-full shrink-0">
      <slot name="footer" />
    </div>
    <TextInput
      class="min-w-full max-w-full w-full"
      :on-send="onSend"
      :disabled="disabled"
      :auto-complete="autoComplete"
      :allowed-input-types="allowedInputTypes"
      :file-processor="fileProcessor"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import type { ContentBlock, Msg, ToolCallBlock } from '@agentscope-ai/agentscope/message';
import MessageBubble from './MessageBubble.vue';
import TextInput from './TextInput.vue';
import Empty from './Empty.vue';

const props = defineProps<{
  msgs: Msg[];
  sending: boolean;
  disabled: boolean;
  onSend: (content: ContentBlock[]) => void;
  onUserConfirm: (
    toolCall: ToolCallBlock,
    confirm: boolean,
    replyId: string,
    rules?: ToolCallBlock['suggested_rules'],
  ) => void;
  autoComplete?: (input: string) => string | null;
  className?: string;
  allowedInputTypes: string[];
  fileProcessor: (file: File) => Promise<ContentBlock | null>;
}>();

defineSlots<{
  footer?: () => any;
  default?: () => any;
}>();

const scrollAreaRef = ref<HTMLDivElement | null>(null);
const wasNearBottom = ref(true);

function handleScroll() {
  const el = scrollAreaRef.value;
  if (!el) return;
  const { scrollTop, scrollHeight, clientHeight } = el;
  wasNearBottom.value = scrollTop + clientHeight >= scrollHeight - 50;
}

watch(
  () => props.msgs,
  () => {
    const el = scrollAreaRef.value;
    if (wasNearBottom.value && el) {
      el.scrollTo({
        top: el.scrollHeight,
      });
    }
  },
);
</script>

<style scoped>
.no-scrollbar::-webkit-scrollbar {
  display: none;
}
.no-scrollbar {
  -ms-overflow-style: none;
  scrollbar-width: none;
}
</style>
