// examples/web_ui/frontend-vue/src/views/chat/index.vue
<template>
  <div class="flex h-full w-full">
    <div class="w-64 border-r bg-background flex flex-col shrink-0">
      <div class="p-3 border-b">
        <div class="text-xs text-muted-foreground mb-2">{{ serverUrl }}</div>
        <div class="flex items-center gap-2">
          <ElSelect
            id="tour-llm-select"
            :model-value="urlAgentId ?? ''"
            :placeholder="t('chat.agent.selectPlaceholder')"
            size="small"
            class="flex-1"
            @change="(id: string) => navigate(`/chat/${id}`)"
          >
            <ElOption
              v-for="agent in agents"
              :key="agent.id"
              :label="agent.data.name"
              :value="agent.id"
            />
          </ElSelect>
          <ElTooltip :content="t('chat.agent.create')">
            <ElButton id="tour-create-agent" size="small" @click="agentCreateOpen = true">
              <Plus class="size-4" />
            </ElButton>
          </ElTooltip>
          <ElTooltip :content="t('chat.agent.edit')">
            <ElButton size="small" :disabled="!urlAgentId" @click="editOpen = true">
              <Settings2 class="size-4" />
            </ElButton>
          </ElTooltip>
          <ElTooltip :content="t('chat.agent.delete')">
            <ElButton size="small" :disabled="!urlAgentId" @click="deleteOpen = true">
              <Trash2 class="size-4 text-destructive" />
            </ElButton>
          </ElTooltip>
        </div>
      </div>
      <div class="flex-1 overflow-auto p-3">
        <div class="flex items-center justify-between mb-2">
          <span class="text-xs font-medium text-muted-foreground">{{ t('chat.session.label') }}</span>
          <ElButton id="tour-create-session" size="small" type="primary" :disabled="!urlAgentId" @click="handleCreateSession">
            <Plus class="size-3" />
          </ElButton>
        </div>
        <div v-if="sessions.length === 0" class="text-center py-8">
          <ElIcon :size="32" class="text-muted-foreground mb-2">
            <MessageSquare />
          </ElIcon>
          <p class="text-sm text-muted-foreground">
            {{ urlAgentId ? t('chat.session.emptyHasAgent') : t('chat.session.emptyNoAgent') }}
          </p>
          <ElButton size="small" class="mt-2" :disabled="!urlAgentId" @click="handleCreateSession">
            {{ t('chat.session.create') }}
          </ElButton>
        </div>
        <div v-else class="space-y-1">
          <div
            v-for="view in sessions"
            :key="(view.session as any).id"
            :class="['flex items-center gap-2 p-2 rounded text-sm cursor-pointer hover:bg-muted group', urlSessionId === (view.session as any).id ? 'bg-muted' : '']"
            @click="navigate(`/chat/${urlAgentId}/${(view.session as any).id}`)"
          >
            <CalendarClock v-if="(view.session as any).source === 'schedule'" class="size-4 shrink-0 text-muted-foreground" />
            <BotMessageSquare v-else class="size-4 shrink-0 text-muted-foreground" />
            <span class="truncate flex-1">{{ (view.session as any).config?.name || (view.session as any).id }}</span>
            <ElDropdown trigger="click" @command="(cmd: string) => handleSessionAction(cmd, view.session as any)">
              <ElButton size="small" text class="opacity-0 group-hover:opacity-100">
                <Ellipsis class="size-3" />
              </ElButton>
              <template #dropdown>
                <ElDropdownMenu>
                  <ElDropdownItem command="rename">
                    <Pencil class="size-3 mr-2" /> {{ t('session-menu.rename') }}
                  </ElDropdownItem>
                  <ElDropdownItem command="export-json">
                    <Download class="size-3 mr-2" /> {{ t('session-menu.exportJson') }}
                  </ElDropdownItem>
                  <ElDropdownItem command="export-md">
                    <Download class="size-3 mr-2" /> {{ t('session-menu.exportMd') }}
                  </ElDropdownItem>
                  <ElDropdownItem command="delete" divided>
                    <Trash2 class="size-3 mr-2" /> {{ t('session-menu.delete') }}
                  </ElDropdownItem>
                </ElDropdownMenu>
              </template>
            </ElDropdown>
          </div>
        </div>
      </div>
    </div>

    <TeamSidebar
      v-if="currentView?.team && effectiveSessionId"
      :team="currentView!.team"
      :current-session-id="effectiveSessionId"
    />

    <div class="flex flex-1 min-w-0">
      <ChatViewport
        :agent-id="effectiveAgentId"
        :session-id="effectiveSessionId"

        :on-team-updated="refetchSessions"
      />
    </div>

    <AgentDialog
      :open="agentCreateOpen"
      @update:open="agentCreateOpen = $event"
      :on-created="refetchAgents"
    />

    <EditAgentDialog
      :open="editOpen"
      :agent="selectedAgent"
      @update:open="editOpen = $event"
      :on-updated="refetchAgents"
    />

    <ElDialog v-model="deleteOpen" :title="deleteDialogTitle" :width="400">
      <p>{{ t('common.deleteDescription') }}</p>
      <template #footer>
        <ElButton @click="deleteOpen = false">{{ t('common.cancel') }}</ElButton>
        <ElButton type="danger" @click="handleDeleteAgent">{{ t('dialog-agent-delete.confirm') }}</ElButton>
      </template>
    </ElDialog>

    <RenameSessionDialog
      :open="renameOpen"
      :current-name="renameName"
      @update:open="renameOpen = $event"
      :on-confirm="handleRenameConfirm"
    />

    <ElDialog v-model="deleteSessionOpen" :title="deleteSessionDialogTitle" :width="400">
      <p>{{ t('common.deleteDescription') }}</p>
      <template #footer>
        <ElButton @click="deleteSessionOpen = false">{{ t('common.cancel') }}</ElButton>
        <ElButton type="danger" @click="handleDeleteSessionConfirm">{{ t('dialog-session-delete.confirm') }}</ElButton>
      </template>
    </ElDialog>

    <ChatTourController
      :agents-count="agents.length"
      :sessions-count="sessions.length"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { useRouter, useRoute } from 'vue-router';
import { ElSelect, ElOption, ElButton, ElDialog, ElTooltip, ElDropdown, ElDropdownMenu, ElDropdownItem, ElIcon } from 'element-plus';
import { Plus, Settings2, Trash2, Ellipsis, Pencil, Download, BotMessageSquare, CalendarClock, MessageSquare } from 'lucide-vue-next';
import { useAgents } from '@/composables/useAgents';
import { useSessions } from '@/composables/useSessions';
import { sessionApi } from '@/api';
import TeamSidebar from '@/components/team/TeamSidebar.vue';
import ChatViewport from './ChatViewport.vue';
import AgentDialog from '@/components/dialog/AgentDialog.vue';
import EditAgentDialog from '@/components/dialog/EditAgentDialog.vue';
import RenameSessionDialog from '@/components/dialog/RenameSessionDialog.vue';
import ChatTourController from '@/components/tour/ChatTourController.vue';
import { useTranslation } from '@/i18n/useI18n';

const router = useRouter();
const route = useRoute();
const { t } = useTranslation();
const { agents, refetch: refetchAgents, remove: removeAgent } = useAgents();

const urlAgentId = computed(() => (route.params.agentId as string) || null);
const urlSessionId = computed(() => (route.params.sessionId as string) || null);
const urlMemberId = computed(() => (route.params.memberId as string) || null);

const agentIdRef = computed(() => urlAgentId.value ?? undefined);

const { sessions, refetch: refetchSessions, create: createSession, update: updateSession, remove: removeSession } = useSessions(agentIdRef as any);

const serverUrl = computed(() => localStorage.getItem('server_url') || '');

const agentCreateOpen = ref(false);
const editOpen = ref(false);
const deleteOpen = ref(false);
const renameOpen = ref(false);
const renameName = ref('');
const renameSessionId = ref<string | null>(null);
const deleteSessionOpen = ref(false);
const sessionToDelete = ref<any>(null);

const selectedAgent = computed(() => agents.value.find((a) => a.id === urlAgentId.value) ?? null);
const currentView = computed(() => sessions.value.find((v) => (v.session as any).id === urlSessionId.value) ?? null);
const sessionToDeleteName = computed(() => sessionToDelete.value?.config?.name || sessionToDelete.value?.id || '');

const deleteDialogTitle = computed(() => t('common.deleteTitle', { name: `${t('dialog-agent-delete.entity')} "${selectedAgent.value?.data?.name ?? ''}"` }));
const deleteSessionDialogTitle = computed(() => t('common.deleteTitle', { name: `${t('dialog-session-delete.entity')} "${sessionToDeleteName.value}"` }));

const focusedMember = computed(() => {
  if (!urlMemberId.value || !currentView.value?.team) return null;
  return (currentView.value.team as any).members.find((m: any) => m.agent.id === urlMemberId.value) ?? null;
});

const effectiveAgentId = computed(() => focusedMember.value?.session_id ? focusedMember.value.agent.id : urlAgentId.value);
const effectiveSessionId = computed(() => focusedMember.value?.session_id ? focusedMember.value.session_id : urlSessionId.value);

function navigate(path: string) {
  router.push(path);
}

watch([agents, urlAgentId], () => {
  if (!urlAgentId.value && agents.value.length > 0) {
    navigate(`/chat/${agents.value[0].id}`);
  }
}, { immediate: true });

watch([urlAgentId, sessions], () => {
  if (!urlAgentId.value || sessions.value.length === 0) return;
  const matches = urlSessionId.value && sessions.value.some((v) => (v.session as any).id === urlSessionId.value);
  if (!matches) {
    navigate(`/chat/${urlAgentId.value}/${(sessions.value[0].session as any).id}`);
  }
}, { immediate: true });

const handleCreateSession = async () => {
  if (!urlAgentId.value) return;
  const seedConfig = (currentView.value?.session as any)?.config ?? (sessions.value[0]?.session as any)?.config;
  const res = await createSession({
    agent_id: urlAgentId.value,
    ...(seedConfig?.chat_model_config ? { chat_model_config: seedConfig.chat_model_config } : {}),
    ...(seedConfig?.fallback_chat_model_config ? { fallback_chat_model_config: seedConfig.fallback_chat_model_config } : {}),
  });
  navigate(`/chat/${urlAgentId.value}/${(res as any).session_id}`);
};

const handleDeleteAgent = async () => {
  if (!selectedAgent.value) return;
  await removeAgent(selectedAgent.value.id);
  router.replace('/chat');
  await refetchAgents();
};

const handleSessionAction = async (cmd: string, session: any) => {
  switch (cmd) {
    case 'rename':
      renameSessionId.value = session.id;
      renameName.value = session.config?.name || session.id;
      renameOpen.value = true;
      break;
    case 'delete':
      sessionToDelete.value = session;
      deleteSessionOpen.value = true;
      break;
    case 'export-json':
    case 'export-md':
      await handleExport(session, cmd === 'export-json' ? 'json' : 'md');
      break;
  }
};

const handleRenameConfirm = async (name: string) => {
  if (!renameSessionId.value) return;
  await updateSession(renameSessionId.value, { name });
  renameOpen.value = false;
};

const handleDeleteSessionConfirm = async () => {
  if (!sessionToDelete.value) return;
  const id = sessionToDelete.value.id;
  await removeSession(id);
  if (id === urlSessionId.value && urlAgentId.value) {
    router.replace(`/chat/${urlAgentId.value}`);
  }
  deleteSessionOpen.value = false;
};

const handleExport = async (session: any, format: 'json' | 'md') => {
  try {
    const res = await (sessionApi as any).exportSession(session.id, effectiveAgentId.value!, format);
    const disposition = (res as any).headers.get('Content-Disposition') ?? '';
    const match = disposition.match(/filename="?(.+?)"?$/);
    const filename = match?.[1] ?? `session-${session.id}.${format}`;
    const blob = await (res as any).blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch { /* handled by client */ }
};
</script>

// examples/web_ui/frontend/src/pages/chat/index.tsx
import {
	BotMessageSquare,
	CalendarClock,
	Download,
	Ellipsis,
	MessageSquareDashed,
	Pencil,
	Plus,
	Settings2,
	Trash2,
} from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import { ChatViewport } from './ChatViewport';
import type { SessionRecord } from '@/api';
import { sessionApi } from '@/api/session';
import { AgentDialog } from '@/components/dialog/AgentDialog';
import { DeleteDialog } from '@/components/dialog/DeleteDialog';
import { EditAgentDialog } from '@/components/dialog/EditAgentDialog';
import { RenameSessionDialog } from '@/components/dialog/RenameSessionDialog';
import { TeamSidebar } from '@/components/team/TeamSidebar';
import { ChatTourController } from '@/components/tour/ChatTourController';
import { Button } from '@/components/ui/button';
import {
	DropdownMenu,
	DropdownMenuContent,
	DropdownMenuItem,
	DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import {
	Empty,
	EmptyHeader,
	EmptyTitle,
	EmptyDescription,
	EmptyContent,
	EmptyMedia,
} from '@/components/ui/empty';
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from '@/components/ui/select';
import {
	Sidebar,
	SidebarContent,
	SidebarFooter,
	SidebarGroup,
	SidebarGroupAction,
	SidebarGroupContent,
	SidebarGroupLabel,
	SidebarHeader,
	SidebarMenu,
	SidebarMenuAction,
	SidebarMenuButton,
	SidebarMenuItem,
	SidebarProvider,
	useSidebar,
} from '@/components/ui/sidebar';
import { AudioProvider } from '@/context/AudioContext';
import { useAgents } from '@/hooks/useAgents';
import { useSessions } from '@/hooks/useSessions';
import { useTranslation } from '@/i18n/useI18n.ts';

/**
 * The chat page's outer shell. Responsibilities split cleanly:
 *
 * - **This component** owns *which* `(agent, session)` is being
 *   viewed. The URL is the single source of truth: every selection
 *   (agent dropdown, session row, team member, new session) is a
 *   ``navigate(...)`` call. State is derived from ``useParams``,
 *   never duplicated in React state. Renders the main left sidebar
 *   (agent picker + session list + create/rename/delete actions) and
 *   computes the ``effective`` ids to feed the chat viewport.
 * - **`ChatViewport`** owns *what* to render for that pair: messages,
 *   model selector, permission mode, workspace drawer, team sidebar.
 *
 * Splitting along this seam means switching between the leader's
 * session and a focused team member is just a prop change for the
 * viewport — the leader's session list stays anchored in this outer
 * sidebar. Driving everything off URL also gets us browser back /
 * forward, shareable links, and refresh-preserving state for free.
 *
 * @returns The chat page JSX.
 */
const ChatPageInner = () => {
	const navigate = useNavigate();
	const {
		agentId: urlAgentId,
		sessionId: urlSessionId,
		memberId: urlMemberId,
	} = useParams<{
		agentId?: string;
		sessionId?: string;
		memberId?: string;
	}>();
	const { t } = useTranslation();
	const { agents, refetch: refetchAgents, remove: removeAgent } = useAgents();
	const {
		sessions,
		refetch: refetchSessions,
		create: createSession,
		update: updateSession,
		remove: removeSession,
	} = useSessions(urlAgentId ?? null);

	const { isMobile, setOpen, setOpenMobile } = useSidebar();
	const [editOpen, setEditOpen] = useState(false);
	const [deleteOpen, setDeleteOpen] = useState(false);
	const [renameOpen, setRenameOpen] = useState(false);
	const [renameSession, setRenameSession] = useState<SessionRecord | null>(null);
	const [deleteSessionOpen, setDeleteSessionOpen] = useState(false);
	const [sessionToDelete, setSessionToDelete] = useState<SessionRecord | null>(null);
	const [menuSessionId, setMenuSessionId] = useState<string | null>(null);

	const selectedAgent = agents.find((a) => a.id === urlAgentId) ?? null;
	const currentView = sessions.find((v) => v.session.id === urlSessionId) ?? null;
	const hasScheduleSessions = sessions.some((v) => v.session.source === 'schedule');

	// "Inner focus" — when the URL carries a third `:memberId` segment
	// the user is drilling into a team member's chat. The main sidebar
	// stays anchored on the outer (leader) session; only the chat
	// viewport follows this inner focus. When `urlMemberId` is
	// undefined or doesn't resolve to a known team member, the inner
	// focus collapses back to the outer (leader) session.
	const focusedMember = urlMemberId
		? (currentView?.team?.members.find((m) => m.agent.id === urlMemberId) ?? null)
		: null;
	const effectiveAgentId =
		focusedMember && focusedMember.session_id ? focusedMember.agent.id : (urlAgentId ?? null);
	const effectiveSessionId =
		focusedMember && focusedMember.session_id
			? focusedMember.session_id
			: (urlSessionId ?? null);

	// Redirect: URL is missing an agent → pick the first one and rewrite
	// the URL in-place (replace so we don't pollute history).
	useEffect(() => {
		if (!urlAgentId && agents.length > 0) {
			navigate(`/chat/${agents[0].id}`, { replace: true });
		}
	}, [agents, urlAgentId, navigate]);

	// Redirect: URL has an agent but no session, or its sessionId no
	// longer exists for this agent → pick the first available session.
	useEffect(() => {
		if (!urlAgentId || sessions.length === 0) return;
		const matches = urlSessionId && sessions.some((v) => v.session.id === urlSessionId);
		if (matches) return;
		navigate(`/chat/${urlAgentId}/${sessions[0].session.id}`, { replace: true });
	}, [urlAgentId, urlSessionId, sessions, navigate]);

	/**
	 * Create a new session under the currently selected agent and
	 * pre-fill it with the model + fallback the currently open session
	 * is using (so "new chat" inherits whatever the user just had
	 * configured). Falls back to any other session under this agent
	 * when there is no current one — keeps the model choice sticky
	 * across "delete last → create new" instead of dropping back to
	 * whatever ChatViewport's auto-pick happens to land on. Navigates
	 * to the freshly created session.
	 */
	const handleCreateSession = async () => {
		if (!urlAgentId) return;
		const seedConfig = currentView?.session.config ?? sessions[0]?.session.config;
		const res = await createSession({
			agent_id: urlAgentId,
			...(seedConfig?.chat_model_config
				? { chat_model_config: seedConfig.chat_model_config }
				: {}),
			...(seedConfig?.fallback_chat_model_config
				? { fallback_chat_model_config: seedConfig.fallback_chat_model_config }
				: {}),
		});
		navigate(`/chat/${urlAgentId}/${res.session_id}`);
	};

	const handleAgentDeleted = async () => {
		navigate('/chat', { replace: true });
		await refetchAgents();
	};

	const handleDeleteSession = async (sessionId: string) => {
		await removeSession(sessionId);
		// If we just removed the session the URL is pointing at, fall
		// back to the parent /chat/:agentId path; the redirect effect
		// will then pick the next available session.
		if (sessionId === urlSessionId && urlAgentId) {
			navigate(`/chat/${urlAgentId}`, { replace: true });
		}
	};

	const requestDeleteSession = (session: SessionRecord) => {
		setSessionToDelete(session);
		setDeleteSessionOpen(true);
	};

	const handleRenameConfirm = async (name: string) => {
		if (!renameSession) return;
		await updateSession(renameSession.id, { name });
	};

	/**
	 * Export a session as JSON or Markdown and trigger a file download.
	 */
	const handleExport = async (session: SessionRecord, format: 'json' | 'md') => {
		try {
			const res = await sessionApi.exportSession(session.id, effectiveAgentId!, format);
			const disposition = res.headers.get('Content-Disposition') ?? '';
			const match = disposition.match(/filename="?(.+?)"?$/);
			const filename = match?.[1] ?? `session-${session.id}.${format}`;
			const blob = await res.blob();
			const url = URL.createObjectURL(blob);
			const a = document.createElement('a');
			a.href = url;
			a.download = filename;
			document.body.appendChild(a);
			a.click();
			document.body.removeChild(a);
			URL.revokeObjectURL(url);
		} catch {
			// Error toast is already shown by client.ts
		}
	};

	return (
		<div className="flex h-full w-full">
			{/*
			 * Desktop stays `collapsible="none"` so the session list sits in
			 * normal flow beside the app rail (AppSidebar). Mobile switches to
			 * `offcanvas`, which makes shadcn's Sidebar render its Sheet overlay
			 * (the drawer we want) — instead of the desktop `fixed left-0`
			 * container, which would otherwise cover the app rail.
			 */}
			<Sidebar collapsible={isMobile ? 'offcanvas' : 'none'} className="border-r">
				<SidebarHeader>
					<div className="flex flex-col gap-y-2">
						<span className="text-muted-foreground text-xs">
							{localStorage.getItem('server_url')}
						</span>
						<div className="flex flex-row gap-x-2 items-center">
							<Select
								value={urlAgentId ?? ''}
								onValueChange={(id) => navigate(`/chat/${id}`)}
							>
								<SelectTrigger className="w-full" size="sm">
									<SelectValue placeholder={t('chat.agent.selectPlaceholder')} />
								</SelectTrigger>
								<SelectContent position="popper">
									{agents.length === 0 ? (
										<Empty className="border-none py-4">
											<EmptyHeader>
												<EmptyTitle>
													{t('chat.agent.emptyTitle')}
												</EmptyTitle>
												<EmptyDescription>
													{t('chat.agent.emptyDescription')}
												</EmptyDescription>
											</EmptyHeader>
										</Empty>
									) : (
										agents.map((agent) => (
											<SelectItem key={agent.id} value={agent.id}>
												{agent.data.name}
											</SelectItem>
										))
									)}
								</SelectContent>
							</Select>
							<Button
								size="icon"
								variant="ghost"
								disabled={!urlAgentId}
								onClick={() => setEditOpen(true)}
							>
								<Settings2 />
							</Button>
							<Button
								size="icon"
								variant="ghost"
								disabled={!urlAgentId}
								onClick={() => setDeleteOpen(true)}
							>
								<Trash2 className="text-destructive" />
							</Button>
						</div>
						<AgentDialog onCreated={refetchAgents} triggerId="tour-create-agent" />
					</div>
				</SidebarHeader>
				<SidebarContent className="my-5">
					<SidebarGroup>
						<SidebarGroupLabel>{t('chat.session.label')}</SidebarGroupLabel>
						<SidebarGroupAction asChild>
							<div>
								<Button
									id="tour-create-session"
									size="icon-xs"
									variant="default"
									disabled={!urlAgentId}
									onClick={handleCreateSession}
								>
									<Plus />
								</Button>
							</div>
						</SidebarGroupAction>
						<SidebarGroupContent>
							{sessions.length === 0 ? (
								<Empty className="border-none py-4 min-h-50">
									<EmptyHeader>
										<EmptyMedia variant="icon">
											<MessageSquareDashed />
										</EmptyMedia>
										<EmptyTitle>{t('chat.session.emptyTitle')}</EmptyTitle>
										<EmptyDescription>
											{urlAgentId
												? t('chat.session.emptyHasAgent')
												: t('chat.session.emptyNoAgent')}
										</EmptyDescription>
									</EmptyHeader>
									<EmptyContent>
										<Button
											variant="outline"
											size="sm"
											disabled={!urlAgentId}
											onClick={handleCreateSession}
										>
											Create Session
										</Button>
									</EmptyContent>
								</Empty>
							) : (
								<SidebarMenu>
									{sessions.map((view) => {
										const session = view.session;
										return (
											<SidebarMenuItem
												key={session.id}
												onContextMenu={(e) => {
													e.preventDefault();
													setMenuSessionId(session.id);
												}}
											>
												<SidebarMenuButton
													isActive={urlSessionId === session.id}
													onClick={() => {
														navigate(
															`/chat/${urlAgentId}/${session.id}`,
														);
														setOpenMobile(false);
													}}
												>
													{hasScheduleSessions &&
														(session.source === 'schedule' ? (
															<CalendarClock />
														) : (
															<BotMessageSquare />
														))}
													<span className="truncate">
														{session.config.name || session.id}
													</span>
												</SidebarMenuButton>
												<SidebarMenuAction showOnHover>
													<DropdownMenu
														open={menuSessionId === session.id}
														onOpenChange={(open) => {
															setMenuSessionId(
																open ? session.id : null,
															);
														}}
													>
														<DropdownMenuTrigger asChild>
															<Ellipsis />
														</DropdownMenuTrigger>
														<DropdownMenuContent
															side="right"
															align="start"
														>
															<DropdownMenuItem
																onClick={() => {
																	setRenameSession(session);
																	setRenameOpen(true);
																}}
															>
																<Pencil />
																{t('session-menu.rename')}
															</DropdownMenuItem>
															<DropdownMenuItem
																onClick={() =>
																	handleExport(session, 'json')
																}
															>
																<Download />
																{t('session-menu.exportJson')}
															</DropdownMenuItem>
															<DropdownMenuItem
																onClick={() =>
																	handleExport(session, 'md')
																}
															>
																<Download />
																{t('session-menu.exportMd')}
															</DropdownMenuItem>
															<DropdownMenuItem
																variant="destructive"
																onClick={() =>
																	requestDeleteSession(session)
																}
															>
																<Trash2 />
																{t('session-menu.delete')}
															</DropdownMenuItem>
														</DropdownMenuContent>
													</DropdownMenu>
												</SidebarMenuAction>
											</SidebarMenuItem>
										);
									})}
								</SidebarMenu>
							)}
						</SidebarGroupContent>
					</SidebarGroup>
				</SidebarContent>
				<SidebarFooter />
			</Sidebar>
			{/*
			 * Team sidebar lives at the outer page level (not inside
			 * ChatViewport) so navigating between leader and member
			 * sessions does NOT unmount it. The team data comes from
			 * the leader's session view, which is stable across that
			 * navigation; only `currentSessionId` changes to drive
			 * row highlighting.
			 */}
			{currentView?.team && effectiveSessionId && (
				<TeamSidebar team={currentView.team} currentSessionId={effectiveSessionId} />
			)}
			<div className="flex flex-1 min-w-0">
				<ChatViewport
					agentId={effectiveAgentId}
					sessionId={effectiveSessionId}
					onTeamUpdated={refetchSessions}
				/>
			</div>
			{selectedAgent && (
				<>
					<EditAgentDialog
						open={editOpen}
						onOpenChange={setEditOpen}
						agent={selectedAgent}
						onUpdated={refetchAgents}
					/>
					<DeleteDialog
						open={deleteOpen}
						onOpenChange={setDeleteOpen}
						title={t('common.deleteTitle', {
							name: `${t('dialog-agent-delete.entity')} "${selectedAgent.data.name}"`,
						})}
						description={t('common.deleteDescription')}
						confirmLabel={t('dialog-agent-delete.confirm')}
						onConfirm={async () => {
							await removeAgent(selectedAgent.id);
							await handleAgentDeleted();
						}}
					/>
				</>
			)}
			<RenameSessionDialog
				open={renameOpen}
				onOpenChange={setRenameOpen}
				currentName={renameSession?.config.name ?? renameSession?.id ?? ''}
				onConfirm={handleRenameConfirm}
			/>
			<DeleteDialog
				open={deleteSessionOpen}
				onOpenChange={setDeleteSessionOpen}
				title={t('common.deleteTitle', {
					name: `${t('dialog-session-delete.entity')} "${sessionToDelete?.config.name || sessionToDelete?.id || ''}"`,
				})}
				description={t('common.deleteDescription')}
				confirmLabel={t('dialog-session-delete.confirm')}
				onConfirm={async () => {
					if (sessionToDelete) {
						await handleDeleteSession(sessionToDelete.id);
					}
				}}
			/>
			<ChatTourController
				agentsCount={agents.length}
				sessionsCount={sessions.length}
				onEnsureSidebarOpen={() => {
					setOpen(true);
					setOpenMobile(true);
				}}
			/>
		</div>
	);
};

export const ChatPage = () => (
	<AudioProvider>
		<SidebarProvider defaultOpen>
			<ChatPageInner />
		</SidebarProvider>
	</AudioProvider>
);
