// examples/web_ui/frontend-vue/src/components/badge/InputTypeBadges.vue
<template>
  <div class="flex flex-row gap-x-1">
    <ElTooltip
      v-for="mod in modalities"
      :key="mod.mainType"
      :content="supportedTooltip(mod)"
    >
      <Component
        :is="mod.icon"
        :size="18"
        :class="hasMatch(mod) ? 'stroke-primary' : 'opacity-30'"
      />
    </ElTooltip>
  </div>
</template>

<script setup lang="ts">
import { ElTooltip } from 'element-plus';
import { Type, Image, Video, AudioLines } from 'lucide-vue-next';
import type { Component } from 'vue';

const props = defineProps<{
  inputTypes: string[];
}>();

interface ModalityConfig {
  mainType: string;
  icon: Component;
  label: string;
  exactMatch?: string;
}

const modalities: ModalityConfig[] = [
  { mainType: 'text', exactMatch: 'text/plain', icon: Type, label: 'text/plain' },
  { mainType: 'image', icon: Image, label: 'image' },
  { mainType: 'video', icon: Video, label: 'video' },
  { mainType: 'audio', icon: AudioLines, label: 'audio' },
];

function hasMatch(mod: ModalityConfig): boolean {
  return mod.exactMatch
    ? props.inputTypes.filter((t) => t === mod.exactMatch).length > 0
    : props.inputTypes.filter((t) => t.startsWith(mod.mainType + '/')).length > 0;
}

function supportedTooltip(mod: ModalityConfig): string {
  const matched = mod.exactMatch
    ? props.inputTypes.filter((t) => t === mod.exactMatch)
    : props.inputTypes.filter((t) => t.startsWith(mod.mainType + '/'));
  return matched.length > 0 ? matched.join(', ') : mod.label;
}
</script>

// examples/web_ui/frontend/src/components/badge/InputTypeBadges.tsx
import { Type, Image, Video, AudioLines } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { cn } from '@/lib/utils';

// ─── Config ───────────────────────────────────────────────────────────────────

interface ModalityConfig {
	/** The MIME main-type prefix this slot matches, e.g. "image" */
	mainType: string;
	/** Lucide icon to render */
	Icon: LucideIcon;
	/** Fallback label shown in tooltip when no subtypes are present */
	label: string;
	/** text/plain is a special case — matched by exact MIME type */
	exactMatch?: string;
}

const MODALITIES: ModalityConfig[] = [
	{ mainType: 'text', exactMatch: 'text/plain', Icon: Type, label: 'text/plain' },
	{ mainType: 'image', Icon: Image, label: 'image' },
	{ mainType: 'video', Icon: Video, label: 'video' },
	{ mainType: 'audio', Icon: AudioLines, label: 'audio' },
];

// ─── Component ────────────────────────────────────────────────────────────────

interface InputTypeBadgesProps {
	/** Array of MIME types, e.g. ["text/plain", "image/jpeg", "audio/mp3"] */
	inputTypes: string[];
	className?: string;
}

export function InputTypeBadges({ inputTypes, className }: InputTypeBadgesProps) {
	return (
		<TooltipProvider>
			<div className={cn('flex flex-row gap-x-1', className)}>
				{MODALITIES.map(({ mainType, exactMatch, Icon, label }) => {
					// Find matching MIME types from the model's input_types
					const matched = exactMatch
						? inputTypes.filter((t) => t === exactMatch)
						: inputTypes.filter((t) => t.startsWith(mainType + '/'));

					const supported = matched.length > 0;
					const tooltipText = supported ? matched.join(', ') : label;

					return (
						<Tooltip key={mainType}>
							<TooltipTrigger asChild>
								<Icon
									size={18}
									className={supported ? 'stroke-primary' : 'opacity-30'}
								/>
							</TooltipTrigger>
							<TooltipContent>
								<span>{tooltipText}</span>
							</TooltipContent>
						</Tooltip>
					);
				})}
			</div>
		</TooltipProvider>
	);
}
